修改提交

diff --git a/.github/workflows/kkstone-build-openwrt_rax3000q.yml b/.github/workflows/kkstone-build-openwrt_rax3000q.yml
--- a/.github/workflows/kkstone-build-openwrt_rax3000q.yml
+++ b/.github/workflows/kkstone-build-openwrt_rax3000q.yml
@@ -199,7 +199,7 @@ jobs:
       run: |
         cd openwrt
         echo -e "$(nproc) thread compile"
-        make -j$(nproc)
+        make -j$(nproc) || echo "make failed step 1 as expect"
         rm -rf feeds/packages/lang/golang
         git clone https://github.com/bluarry/packages_openwrt_lang_golang.git -b 21.x feeds/packages/lang/golang
         ./scripts/feeds update -i
